# Práctica Clase 3

## Numpy

In [3]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [4]:
lista_ = [1,2,3,4,6]
array_ = np.array(lista_)
print(lista_)
print(array_)

print(lista_ * 2)
print(array_ * 2)

"""
veo que las operaciones caen sobre cada elemento del array, no asi como
en la lista. Que habria que recorrerla entera
aqui estoy poniendo operaciones que se pueden hacer. En realidad todas las
operaciones se pueden hacer (las basicas), pero las que son
vectorizadas tienen resultados diferentes.
"""

[1, 2, 3, 4, 6]
[1 2 3 4 6]
[1, 2, 3, 4, 6, 1, 2, 3, 4, 6]
[ 2  4  6  8 12]


'\nveo que las operaciones caen sobre cada elemento del array, no asi como\nen la lista. Que habria que recorrerla entera\naqui estoy poniendo operaciones que se pueden hacer. En realidad todas las\noperaciones se pueden hacer (las basicas), pero las que son\nvectorizadas tienen resultados diferentes.\n'

In [5]:
array_ + 1
#lista_ + 1 esto no se puede, me da error
lista_ * 1 # esto si se puede
#lista_ ** 2 esto no se puede

[1, 2, 3, 4, 6]

In [6]:
# formas de crear un arreglo rapidamente
arreglo_1 = np.arange(8) # arranca de 0 a 7 - 8 elementos
print(arreglo_1)

[0 1 2 3 4 5 6 7]


A partir de una lista podemos crear un arreglo de numpy

In [7]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [8]:
#en esta funcion podemos ver que usando una funcion podemos sumar
#todos los elementos de un arreglo. Pero para una lista, tendriamos que recorrerla.
print(arreglo.sum())

15


In [10]:
#aca vemos que para sumar todos los elementos tenemos que iterar en la lista.
suma =0
for i in lista:
  suma += i
print(suma)

15


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [17]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [ ]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
arreglo = arreglo + 1

In [ ]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [ ]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

3. Sumar todos los elementos

In [ ]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [11]:
arreglo.shape

(6,)

In [25]:
#el atributo shape me devuelve una tupla que indica la dimension de arreglo.
arreglo = np.arange(0,8,2) #aca tengo el comienzo en 0, va hasta 8 y el paso = 2
print(arreglo)
arreglo.shape

[0 2 4 6]


(4,)

In [31]:
#aqui voy a crear un arreglo bidimensional tiene que correspoander las filas y las columnas.
arreglo_bi = np.array([[1,2,3],[4,5,6]])
print(arreglo_bi, ". Shape = ",arreglo_bi.shape, "\n")
arreglo_bi.shape

[[1 2 3]
 [4 5 6]] . Shape =  (2, 3) 



(2, 3)

In [19]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [ ]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [ ]:
a3 = a1 * a2
a3.shape

(2, 4)

In [ ]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [35]:
arreglo = np.arange(9)
print(arreglo)
arreglo_equies = np.linspace(0,9,100)
print(arreglo_equies)

[0 1 2 3 4 5 6 7 8]
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [42]:
arreglo = np.arange(10,100)
print(arreglo)
mask = arreglo % 3 == 0
resultado = arreglo[mask]
print(resultado)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [23]:
import numpy as np
arreglo = np.zeros((5,10)) # aqui la funcion zero espera una tupla, por eso el doble parentesis
print(arreglo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
arreglo[1,:] = 1
arreglo[3,:] = 1
print(arreglo)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
arreglo[:, 2] = 2
arreglo[:, 7] = 2
print(arreglo)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [26]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[197.28720153, 133.99544739, 182.35159416],
        [118.13094146, 138.27027149, 193.73023921]],

       [[119.22175609, 180.0089955 , 122.08483784],
        [174.26751587, 191.1763878 , 126.28573021]],

       [[184.54471364, 122.2737904 , 152.73881775],
        [117.92948099, 167.65762922, 159.29744368]],

       [[116.92851255, 181.80384406, 108.15083238],
        [116.59991649, 121.36077696, 131.09439309]]])

In [ ]:
a = np.random.random((4,4))

In [ ]:
a

array([[0.48673571, 0.50465005, 0.33227167, 0.86611167],
       [0.14502147, 0.13692842, 0.56804006, 0.89177045],
       [0.78692331, 0.25942502, 0.88516122, 0.32876297],
       [0.78919257, 0.64347772, 0.02402004, 0.66363368]])

In [ ]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [ ]:
a

array([[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [ ]:
a.sum()

519

In [ ]:
a.std()

23.924904214367643

In [ ]:
a.sort(axis=1)

In [ ]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [ ]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [ ]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

(1, 4, 6)

In [ ]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [ ]:
a = np.matrix([[1,2,3,4,5,6]])
print(a)

[[1 2 3 4 5 6]]


In [ ]:
b = np.matrix([[1],[2],[3],[4],[5],[6]])
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
c = a * b
print(c)

[[91]]


In [ ]:
d = b * a
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
