In [2]:
import numpy as np


In [8]:
lista = [1,2,3,4,5,6]
print(lista)

[1, 2, 3, 4, 5, 6]


In [7]:
array = np.array(lista)
print(array)

[1 2 3 4 5 6]


Todos los elementos de un array tiene que ser de mismo tipo, osea, enteros, flotantes, string, etc. Si la lista es de distintos elementos el metodo array() los convierte en uno solo.

In [17]:
# lista + 2 si lo quisiera hacer tendria que iterar en toda la lista
for i in range(0,len(lista)):
    lista[i] = lista[i] + 2
lista

[3, 4, 5, 6, 7, 8]

In [20]:
#en cambio en un array lo puedo hacer
array + 2 # cabe aclarar que no modifica el array original
print(array + 2)

[3 4 5 6 7 8]


In [13]:
lista *2 #esto me devuelve 2 lista concatenadas

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [31]:
#formas de crear un arreglo rapidamente

arreglo = np.arange(5)
print("Arreglo de 5 elementos: ",arreglo)

arreglo2 = np.arange(2,9)
print("Areglo entre 2 y 9 (No toma el ultimo valor)", arreglo2)

arreglo3 = np.arange(1,15,2)
print("Areglo entre 1 y 15 pero de 2 pasos", arreglo3)



Arreglo de 5 elementos:  [0 1 2 3 4]
Areglo entre 2 y 9 (No toma el ultimo valor) [2 3 4 5 6 7 8]
Areglo entre 1 y 15 pero de 2 pasos [ 1  3  5  7  9 11 13]


In [33]:
#otra cosa para tener en cuenta es que en las lista no esta la funcion sum(), en los array si, podemos sumar todos sus elementos 
print(array)
array.sum()

[1 2 3 4 5 6]


21

In [36]:
print(lista)
#lista.sum()
suma = 0
for i in lista:
    suma += i
print(suma)

[3, 4, 5, 6, 7, 8]
33


In [38]:
array_bi = np.array([[1,2,3],[4,5,6]])
array_bi

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
array_bi.shape

(2, 3)

In [42]:
array_bi_c = np.array([[1,2,3,4,5,6]])
array_bi_c.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [43]:
arreglo = np.linspace(0,9,100)
print(arreglo)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [44]:
arreglo_0_100 = np.arange(0,100)
print(arreglo_0_100)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [45]:
mask = arreglo_0_100 % 3 == 0

In [47]:
print(arreglo_0_100[mask])

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [53]:
arreglo_5_10 = np.zeros((5,10))
print(arreglo_5_10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
arreglo_5_10[1,:] = 1
arreglo_5_10[3,:] = 1
print(arreglo_5_10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
arreglo_5_10[:,2] = 2
arreglo_5_10[:,7] = 2
print(arreglo_5_10)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


In [71]:
array_rand = np.random.random(3)
print(array_rand)

[0.17844553 0.63096242 0.2516807 ]
